version: '3.9'

services:
  dev-db:
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ./.env

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

name: fastapi-development
